// Mock Beeper Messages for Demo Purposes
// This simulates what the Beeper integration would look like when working

const now = Date.now();
const oneHour = 60 * 60 * 1000;
const oneDay = 24 * oneHour;

export const mockBeeperMessages = [
  // iMessage Messages
  {
    id: 'imsg-001',
    platform: 'imessage',
    from_name: 'Mom',
    from_contact: '+1-555-0101',
    body: 'dont forget dinner this sunday at 6!! ur dad wants to try that new italian place 🍝',
    snippet: 'dont forget dinner this sunday at 6!! ur dad wants',
    room_name: 'Mom',
    room_id: 'imsg-room-001',
    date: new Date(now - 2 * oneHour).toISOString(),
    timestamp: now - 2 * oneHour,
    category: 'EVENT',
    urgency: 'medium',
    confidence: 0.92,
    is_group_message: false,
    has_attachments: false,
    is_unread: false
  },
  {
    id: 'imsg-002',
    platform: 'imessage',
    from_name: 'Sarah Chen',
    from_contact: '+1-555-0102',
    body: 'heyy r u free for coffee tmrw morning? wanna catch up about that project idea we talked about ☕',
    snippet: 'heyy r u free for coffee tmrw morning? wanna catch up',
    room_name: 'Sarah Chen',
    room_id: 'imsg-room-002',
    date: new Date(now - 5 * oneHour).toISOString(),
    timestamp: now - 5 * oneHour,
    category: 'SOCIAL',
    urgency: 'low',
    confidence: 0.88,
    is_group_message: false,
    has_attachments: false,
    is_unread: false
  },
  {
    id: 'imsg-003',
    platform: 'imessage',
    from_name: 'Jake Martinez',
    from_contact: '+1-555-0103',
    body: 'DUDEEE concert tix go on sale in 30 min!!! dont forget 🎸🔥',
    snippet: 'DUDEEE concert tix go on sale in 30 min!!! dont forget',
    room_name: 'Jake Martinez',
    room_id: 'imsg-room-003',
    date: new Date(now - 30 * 60 * 1000).toISOString(),
    timestamp: now - 30 * 60 * 1000,
    category: 'URGENT',
    urgency: 'high',
    confidence: 0.95,
    is_group_message: false,
    has_attachments: false,
    is_unread: true
  },
  {
    id: 'imsg-004',
    platform: 'imessage',
    from_name: 'Emma Wilson',
    from_contact: '+1-555-0104',
    body: 'thx for sending those docs! ill look at them and lyk by eod 👍',
    snippet: 'thx for sending those docs! ill look at them and lyk',
    room_name: 'Emma Wilson',
    room_id: 'imsg-room-004',
    date: new Date(now - 1 * oneDay).toISOString(),
    timestamp: now - 1 * oneDay,
    category: 'TODO',
    urgency: 'medium',
    confidence: 0.85,
    is_group_message: false,
    has_attachments: false,
    is_unread: false
  },
  {
    id: 'imsg-005',
    platform: 'imessage',
    from_name: 'Study Group',
    from_contact: 'group-001',
    body: 'Alex: library tmrw at 3pm to work on final project??',
    snippet: 'Alex: library tmrw at 3pm to work on final project??',
    room_name: 'Study Group',
    room_id: 'imsg-room-005',
    date: new Date(now - 8 * oneHour).toISOString(),
    timestamp: now - 8 * oneHour,
    category: 'EVENT',
    urgency: 'medium',
    confidence: 0.90,
    is_group_message: true,
    has_attachments: false,
    is_unread: false
  },
  {
    id: 'imsg-006',
    platform: 'imessage',
    from_name: 'Dad',
    from_contact: '+1-555-0105',
    body: 'hey ur car insurance is due next week btw. remember to pay it!',
    snippet: 'hey ur car insurance is due next week btw. remember',
    room_name: 'Dad',
    room_id: 'imsg-room-006',
    date: new Date(now - 1.5 * oneDay).toISOString(),
    timestamp: now - 1.5 * oneDay,
    category: 'TODO',
    urgency: 'high',
    confidence: 0.93,
    is_group_message: false,
    has_attachments: false,
    is_unread: false
  },
  {
    id: 'imsg-007',
    platform: 'imessage',
    from_name: 'Best Friends 🎉',
    from_contact: 'group-002',
    body: 'Michael: whos down for beach volleyball this sat? 🏐☀️',
    snippet: 'Michael: whos down for beach volleyball this sat? 🏐☀️',
    room_name: 'Best Friends 🎉',
    room_id: 'imsg-room-007',
    date: new Date(now - 12 * oneHour).toISOString(),
    timestamp: now - 12 * oneHour,
    category: 'SOCIAL',
    urgency: 'low',
    confidence: 0.87,
    is_group_message: true,
    has_attachments: false,
    is_unread: false
  },

  // WhatsApp Messages
  {
    id: 'wa-001',
    platform: 'whatsapp',
    from_name: 'Priya Sharma',
    from_contact: '+91-9876543210',
    body: 'omg just saw ur story!! where was that pic taken?? looks so gooood 📸✨',
    snippet: 'omg just saw ur story!! where was that pic taken?? looks',
    room_name: 'Priya Sharma',
    room_id: 'wa-room-001',
    date: new Date(now - 4 * oneHour).toISOString(),
    timestamp: now - 4 * oneHour,
    category: 'SOCIAL',
    urgency: 'low',
    confidence: 0.89,
    is_group_message: false,
    has_attachments: false,
    is_unread: false
  },
  {
    id: 'wa-002',
    platform: 'whatsapp',
    from_name: 'Family Chat',
    from_contact: 'group-003',
    body: 'Grandma: everyone pls come over for thanksgiving!! im making all ur fav dishes 🦃❤️',
    snippet: 'Grandma: everyone pls come over for thanksgiving!! im making',
    room_name: 'Family Chat',
    room_id: 'wa-room-002',
    date: new Date(now - 6 * oneHour).toISOString(),
    timestamp: now - 6 * oneHour,
    category: 'EVENT',
    urgency: 'medium',
    confidence: 0.94,
    is_group_message: true,
    has_attachments: false,
    is_unread: false
  },
  {
    id: 'wa-003',
    platform: 'whatsapp',
    from_name: 'Carlos Rodriguez',
    from_contact: '+52-1234567890',
    body: 'hey can u send me the link to that article u mentioned? need it for presentation tmrw 🙏',
    snippet: 'hey can u send me the link to that article u mentioned?',
    room_name: 'Carlos Rodriguez',
    room_id: 'wa-room-003',
    date: new Date(now - 3 * oneHour).toISOString(),
    timestamp: now - 3 * oneHour,
    category: 'TODO',
    urgency: 'medium',
    confidence: 0.91,
    is_group_message: false,
    has_attachments: false,
    is_unread: true
  },
  {
    id: 'wa-004',
    platform: 'whatsapp',
    from_name: 'Roommates',
    from_contact: 'group-004',
    body: 'Lisa: reminder rent is due friday!! pls venmo me ur share asap 💰',
    snippet: 'Lisa: reminder rent is due friday!! pls venmo me ur share',
    room_name: 'Roommates',
    room_id: 'wa-room-004',
    date: new Date(now - 10 * oneHour).toISOString(),
    timestamp: now - 10 * oneHour,
    category: 'TODO',
    urgency: 'high',
    confidence: 0.96,
    is_group_message: true,
    has_attachments: false,
    is_unread: false
  },
  {
    id: 'wa-005',
    platform: 'whatsapp',
    from_name: 'Aisha Patel',
    from_contact: '+44-7700900123',
    body: 'omggg did u see the email from prof?? assignment deadline moved to next week!! 🎉😭',
    snippet: 'omggg did u see the email from prof?? assignment deadline',
    room_name: 'Aisha Patel',
    room_id: 'wa-room-005',
    date: new Date(now - 7 * oneHour).toISOString(),
    timestamp: now - 7 * oneHour,
    category: 'INFORMATIONAL',
    urgency: 'low',
    confidence: 0.86,
    is_group_message: false,
    has_attachments: false,
    is_unread: false
  },
  {
    id: 'wa-006',
    platform: 'whatsapp',
    from_name: 'Workout Crew 💪',
    from_contact: 'group-005',
    body: 'David: 6am gym sesh tmrw. whos in?? last week was way too easy lol 😤💪',
    snippet: 'David: 6am gym sesh tmrw. whos in?? last week was way',
    room_name: 'Workout Crew 💪',
    room_id: 'wa-room-006',
    date: new Date(now - 14 * oneHour).toISOString(),
    timestamp: now - 14 * oneHour,
    category: 'SOCIAL',
    urgency: 'low',
    confidence: 0.88,
    is_group_message: true,
    has_attachments: false,
    is_unread: false
  },
  {
    id: 'wa-007',
    platform: 'whatsapp',
    from_name: 'Sophie Laurent',
    from_contact: '+33-612345678',
    body: 'heyy ur package arrived at front desk btw! pick it up whenever 📦',
    snippet: 'heyy ur package arrived at front desk btw! pick it up',
    room_name: 'Sophie Laurent',
    room_id: 'wa-room-007',
    date: new Date(now - 1 * oneHour).toISOString(),
    timestamp: now - 1 * oneHour,
    category: 'TODO',
    urgency: 'low',
    confidence: 0.90,
    is_group_message: false,
    has_attachments: false,
    is_unread: true
  },

  // Telegram Messages
  {
    id: 'tg-001',
    platform: 'telegram',
    from_name: 'Tech News Daily',
    from_contact: '@technewsdaily',
    body: '🚀 breaking: new AI model just dropped with 10x perf improvements 👀 check it out t.me/technews/1234',
    snippet: '🚀 breaking: new AI model just dropped with 10x perf improvements',
    room_name: 'Tech News Daily',
    room_id: 'tg-room-001',
    date: new Date(now - 45 * 60 * 1000).toISOString(),
    timestamp: now - 45 * 60 * 1000,
    category: 'INFORMATIONAL',
    urgency: 'low',
    confidence: 0.84,
    is_group_message: false,
    has_attachments: true,
    is_unread: true
  },
  {
    id: 'tg-002',
    platform: 'telegram',
    from_name: 'Developers Hub',
    from_contact: 'group-006',
    body: 'Anna K: anyone got experience w websockets?? need help debugging connection stuff :/',
    snippet: 'Anna K: anyone got experience w websockets?? need help debugging',
    room_name: 'Developers Hub',
    room_id: 'tg-room-002',
    date: new Date(now - 9 * oneHour).toISOString(),
    timestamp: now - 9 * oneHour,
    category: 'SOCIAL',
    urgency: 'low',
    confidence: 0.87,
    is_group_message: true,
    has_attachments: false,
    is_unread: false
  },
  {
    id: 'tg-003',
    platform: 'telegram',
    from_name: 'Marcus Kim',
    from_contact: '@marcuskim',
    body: 'just pushed latest changes to repo. can u review the pr when u get a sec?',
    snippet: 'just pushed latest changes to repo. can u review the pr',
    room_name: 'Marcus Kim',
    room_id: 'tg-room-003',
    date: new Date(now - 11 * oneHour).toISOString(),
    timestamp: now - 11 * oneHour,
    category: 'TODO',
    urgency: 'medium',
    confidence: 0.92,
    is_group_message: false,
    has_attachments: false,
    is_unread: false
  },
  {
    id: 'tg-004',
    platform: 'telegram',
    from_name: 'Crypto Alerts',
    from_contact: '@cryptoalerts',
    body: '⚠️ ALERT: btc just dropped 5% in last hr!! market goin crazy rn 📉',
    snippet: '⚠️ ALERT: btc just dropped 5% in last hr!! market goin',
    room_name: 'Crypto Alerts',
    room_id: 'tg-room-004',
    date: new Date(now - 20 * 60 * 1000).toISOString(),
    timestamp: now - 20 * 60 * 1000,
    category: 'URGENT',
    urgency: 'high',
    confidence: 0.89,
    is_group_message: false,
    has_attachments: false,
    is_unread: true
  },
  {
    id: 'tg-005',
    platform: 'telegram',
    from_name: 'Startup Community',
    from_contact: 'group-007',
    body: 'founder Q&A starts in 15 min!! join here: t.me/startup/event 🚀',
    snippet: 'founder Q&A starts in 15 min!! join here: t.me/startup/event',
    room_name: 'Startup Community',
    room_id: 'tg-room-005',
    date: new Date(now - 15 * 60 * 1000).toISOString(),
    timestamp: now - 15 * 60 * 1000,
    category: 'EVENT',
    urgency: 'high',
    confidence: 0.94,
    is_group_message: true,
    has_attachments: true,
    is_unread: true
  },

  // Discord Messages
  {
    id: 'dc-001',
    platform: 'discord',
    from_name: 'GameNight',
    from_contact: 'guild-001',
    body: '@everyone raid starting in 30 min!! make sure ur geared up lets gooo ⚔️🔥',
    snippet: '@everyone raid starting in 30 min!! make sure ur geared',
    room_name: 'GameNight - #general',
    room_id: 'dc-room-001',
    date: new Date(now - 25 * 60 * 1000).toISOString(),
    timestamp: now - 25 * 60 * 1000,
    category: 'EVENT',
    urgency: 'medium',
    confidence: 0.91,
    is_group_message: true,
    has_attachments: false,
    is_unread: true
  },
  {
    id: 'dc-002',
    platform: 'discord',
    from_name: 'CodeReview',
    from_contact: 'guild-002',
    body: 'TechLead: code review sesh tmrw at 2pm. pls have ur PRs ready 👨‍💻',
    snippet: 'TechLead: code review sesh tmrw at 2pm. pls have ur PRs',
    room_name: 'CodeReview - #announcements',
    room_id: 'dc-room-002',
    date: new Date(now - 16 * oneHour).toISOString(),
    timestamp: now - 16 * oneHour,
    category: 'TODO',
    urgency: 'medium',
    confidence: 0.93,
    is_group_message: true,
    has_attachments: false,
    is_unread: false
  },
  {
    id: 'dc-003',
    platform: 'discord',
    from_name: 'Alex Rivers',
    from_contact: 'user-001',
    body: 'yoo saw ur msg in the server. wanna hop on call to talk about that project?',
    snippet: 'yoo saw ur msg in the server. wanna hop on call to talk',
    room_name: 'Alex Rivers (DM)',
    room_id: 'dc-room-003',
    date: new Date(now - 5 * oneHour).toISOString(),
    timestamp: now - 5 * oneHour,
    category: 'SOCIAL',
    urgency: 'low',
    confidence: 0.86,
    is_group_message: false,
    has_attachments: false,
    is_unread: false
  },
  {
    id: 'dc-004',
    platform: 'discord',
    from_name: 'Study Server',
    from_contact: 'guild-003',
    body: 'ModTeam: 🎓 study session for midterm starts NOW in vc 1!! get in here',
    snippet: '🎓 study session for midterm starts NOW in vc 1!! get',
    room_name: 'Study Server - #study-hall',
    room_id: 'dc-room-004',
    date: new Date(now - 10 * 60 * 1000).toISOString(),
    timestamp: now - 10 * 60 * 1000,
    category: 'EVENT',
    urgency: 'high',
    confidence: 0.95,
    is_group_message: true,
    has_attachments: false,
    is_unread: true
  },

  // Slack Messages
  {
    id: 'sl-001',
    platform: 'slack',
    from_name: 'Engineering Team',
    from_contact: 'channel-001',
    body: 'Sarah PM: sprint planning moved to thurs 10am btw. updated cal invite sent 📅',
    snippet: 'Sarah PM: sprint planning moved to thurs 10am btw. updated',
    room_name: '#engineering',
    room_id: 'sl-room-001',
    date: new Date(now - 2 * oneDay).toISOString(),
    timestamp: now - 2 * oneDay,
    category: 'EVENT',
    urgency: 'medium',
    confidence: 0.92,
    is_group_message: true,
    has_attachments: false,
    is_unread: false
  },
  {
    id: 'sl-002',
    platform: 'slack',
    from_name: 'Jennifer Park',
    from_contact: 'user-002',
    body: 'quick q - can u review the design mockups i shared in figma? need feedback by eod pls 🙏',
    snippet: 'quick q - can u review the design mockups i shared in',
    room_name: 'Jennifer Park (DM)',
    room_id: 'sl-room-002',
    date: new Date(now - 6 * oneHour).toISOString(),
    timestamp: now - 6 * oneHour,
    category: 'TODO',
    urgency: 'high',
    confidence: 0.94,
    is_group_message: false,
    has_attachments: true,
    is_unread: true
  },
  {
    id: 'sl-003',
    platform: 'slack',
    from_name: 'Random',
    from_contact: 'channel-002',
    body: '🎉 office party this friday at 5!! pizza n games. rsvp in thread',
    snippet: '🎉 office party this friday at 5!! pizza n games. rsvp',
    room_name: '#random',
    room_id: 'sl-room-003',
    date: new Date(now - 1 * oneDay).toISOString(),
    timestamp: now - 1 * oneDay,
    category: 'SOCIAL',
    urgency: 'low',
    confidence: 0.89,
    is_group_message: true,
    has_attachments: false,
    is_unread: false
  },
  {
    id: 'sl-004',
    platform: 'slack',
    from_name: 'DevOps',
    from_contact: 'channel-003',
    body: '⚠️ prod deployment tonight at 11pm pst. expect brief downtime 🚨',
    snippet: '⚠️ prod deployment tonight at 11pm pst. expect brief downtime',
    room_name: '#devops',
    room_id: 'sl-room-004',
    date: new Date(now - 4 * oneHour).toISOString(),
    timestamp: now - 4 * oneHour,
    category: 'URGENT',
    urgency: 'high',
    confidence: 0.97,
    is_group_message: true,
    has_attachments: false,
    is_unread: true
  },
  {
    id: 'sl-005',
    platform: 'slack',
    from_name: 'Tom Anderson',
    from_contact: 'user-003',
    body: 'thx for jumping on that bug fix so fast!! appreciate it 🙏💯',
    snippet: 'thx for jumping on that bug fix so fast!! appreciate it',
    room_name: 'Tom Anderson (DM)',
    room_id: 'sl-room-005',
    date: new Date(now - 8 * oneHour).toISOString(),
    timestamp: now - 8 * oneHour,
    category: 'SOCIAL',
    urgency: 'low',
    confidence: 0.85,
    is_group_message: false,
    has_attachments: false,
    is_unread: false
  }
];
